project:
  type: website
  output-dir: docs

website:
  title: "Em Detwiler's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Stat-244-SC.qmd
        text: Stat-244-SC

format:
  html:
    theme: minty
    fontcolor: 'pink'
    css: styles.css
    toc: true

editor: visual

